
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # build an arch linux package for cli
    - name: Arch Linux PKGBUILD builder action
      uses: 2m/arch-pkgbuild-builder@v1.16
      with:
        pkgname: '/pkg/arch/minutecat-git/'
        target: 'pkgbuild'
